### ISSUE TITLE
How to check domain name expiration time in batches, for example, I have 100 domain names that need to be monitored, what should I do,

### ISSUE THREAD

**Issue by p0rietea** [gabe565/domain-watch#37]
How to check domain name expiration time in batches, for example, I have 100 domain names that need to be monitored, what should I do,

**Comment by gabe565** [comment]
Sorry for the late reply. Somehow I missed this issue until now.

You can pass a list of domains, and it will watch all of them. Either by running something like `domain-watch example.com example.org` or by setting the `WATCH_DOMAINS` env, like `WATCH_DOMAINS=example.com,example.org`.
